# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "zcdump"
version = "0.1.0"
edition.workspace = true
description = "Fetch zygote CA and user certificates and bundle them as PKCS#12"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "uc-cert-p12-fetch"
path = "src/main.rs"

[dependencies]
