# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := zcdump
BIN := uc-cert-p12-fetch
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := zcdump

include ../rust.mk
