# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := trust_ca
BIN := uc-cert-trust
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := trust_ca

include ../rust.mk
