# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := gotorepo
BIN := uc-repo-open
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := gotorepo

include ../rust.mk
