[package]
name = "pg"
version = "0.1.0"
edition = "2024"
description = "PostgreSQL CLI for local podman instances, schema management and queries"
authors = ["Hamed Ghasemzadeh <hg@evgnomon.org>"]
publish = false

[[bin]]
name = "pg"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
flate2 = "1"
postgres = { version = "0.19", features = ["with-chrono-0_4", "with-serde_json-1", "with-uuid-1"] }
rust_decimal = { version = "1", features = ["db-postgres"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
uuid = "1"

[profile.release]
strip = true
lto = true
codegen-units = 1
