# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := pg
BIN := uc-db-pg
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := pg

include ../rust.mk
