# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "ucversion"
version = "0.1.0"
edition.workspace = true
description = "Print the latest tag on master or the current branch name"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "uc-repo-version"
path = "src/main.rs"

[dependencies]
