.PHONY: ci
 
ci:
	@echo "══════════════════════════════════════════"
	@echo "  CI Environment"
	@echo "══════════════════════════════════════════"
	@echo "  CI_SYSTEM:        $(CI_SYSTEM)"
	@echo "  CI_EVENT:         $(CI_EVENT)"
	@echo "  CI_REF:           $(CI_REF)"
	@echo "  CI_BASE_REF:      $(CI_BASE_REF)"
	@echo "  CI_HEAD_REF:      $(CI_HEAD_REF)"
	@echo "  CI_COMMIT:        $(CI_COMMIT)"
	@echo "  CI_COMMIT_SHORT:  $(CI_COMMIT_SHORT)"
	@echo "  CI_COMMIT_MSG:    $(CI_COMMIT_MSG)"
	@echo "  CI_BRANCH:        $(CI_BRANCH)"
	@echo "  CI_TARGET_BRANCH: $(CI_TARGET_BRANCH)"
	@echo "  CI_REPO:          $(CI_REPO)"
	@echo "  CI_REPO_URL:      $(CI_REPO_URL)"
	@echo "  CI_PR_NUMBER:     $(CI_PR_NUMBER)"
	@echo "  CI_TAG:           $(CI_TAG)"
	@echo "  CI_RUN_ID:        $(CI_RUN_ID)"
	@echo "  CI_RUN_URL:       $(CI_RUN_URL)"
	@echo "  CI_ACTOR:         $(CI_ACTOR)"
	@echo "  CI_ACTOR_EMAIL:   $(CI_ACTOR_EMAIL)"
	@echo "  CI_PIPELINE_NAME: $(CI_PIPELINE_NAME)"
	@echo "  CI_JOB_NAME:      $(CI_JOB_NAME)"
	@echo "  CI_TIMESTAMP:     $(CI_TIMESTAMP)"
	@echo "  CI_WORKSPACE:     $(CI_WORKSPACE)"
	@echo "══════════════════════════════════════════"
 
