# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "num_argv"
version = "0.1.0"
edition = "2024"
description = "Print argc and each argv element with its index"
license = "HGL"
authors = ["Hamed Ghasemzadeh <hg@evgnomon.org>"]
publish = false

[[bin]]
name = "num_argv"
path = "src/main.rs"

[dependencies]

[profile.release]
strip = true
lto = true
codegen-units = 1
