# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := num_argv
BIN := uc-sys-argv
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := num_argv

include ../rust.mk
