# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := set_git_conf
BIN := uc-repo-git-config
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := set_git_conf

include ../rust.mk
