# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := plat
BIN := uc-cloud-play-host
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := plat

include ../rust.mk
