# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := confmap
BIN := uc-db-resources-configmap
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := confmap

include ../rust.mk
