# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "wdoctl"
version = "0.1.0"
edition = "2024"
description = "Run doctl with the repository's DigitalOcean token"
license = "HGL"
authors = ["Hamed Ghasemzadeh <hg@evgnomon.org>"]
publish = false

[[bin]]
name = "wdoctl"
path = "src/main.rs"

[dependencies]
serde_json = "1"

[profile.release]
strip = true
lto = true
codegen-units = 1
