# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := wdoctl
BIN := uc-cloud-do
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := wdoctl

include ../rust.mk
