# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "ensure_vault"
version = "0.1.0"
edition = "2024"
description = "Ensure the repository vault and secret file exist and print the vault name"
license = "HGL"
authors = ["Hamed Ghasemzadeh <hg@evgnomon.org>"]
publish = false

[[bin]]
name = "ensure_vault"
path = "src/main.rs"

[dependencies]
libc = "0.2"

[profile.release]
strip = true
lto = true
codegen-units = 1
