# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "diga"
version = "0.1.0"
edition.workspace = true
description = "Print only the A records of a DNS lookup with dig"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "uc-net-dig"
path = "src/main.rs"

[dependencies]
