# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := annabelle
BIN := uc-cloud-play-ssh
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := annabelle

include ../rust.mk
