# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := tidycsv
BIN := uc-data-tidy
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := tidycsv

include ../rust.mk
