# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "mkp12"
version = "0.1.0"
edition.workspace = true
description = "Bundle a zygote function key and certificate into PKCS#12"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "mkp12"
path = "src/main.rs"

[dependencies]
