# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := mkp12
BIN := uc-cert-p12-bundle
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := mkp12

include ../rust.mk
