# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "vi"
version = "0.1.0"
edition = "2024"
description = "Hardened vim without config, plugins, backups or modelines"
license = "HGL"
authors = ["Hamed Ghasemzadeh <hg@evgnomon.org>"]
publish = false

[[bin]]
name = "vi"
path = "src/main.rs"

[dependencies]

[profile.release]
strip = true
lto = true
codegen-units = 1
