# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "vi"
version = "0.1.0"
edition.workspace = true
description = "Hardened vim without config, plugins, backups or modelines"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "vi"
path = "src/main.rs"

[dependencies]
