# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := mkpod
BIN := uc-db-resources-pods
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := mkpod

include ../rust.mk
