# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := sqlize
BIN := uc-db-migrate
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := sqlize

include ../rust.mk
