# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := ysys
BIN := uc-db-resources-yaml
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := ysys

include ../rust.mk
