use postgres::{Client, Row};

use crate::db::{connect, die, err_text};

type Result<T> = std::result::Result<T, postgres::Error>;

pub fn run(database: &str, schema: &str) {
    let mut client = connect(Some(database));
    match dump(&mut client, database, schema) {
        Ok(out) => println!("{}", out.join("\n")),
        Err(e) => die(format!("Error: {}", err_text(&e))),
    }
}

fn dump(client: &mut Client, database: &str, schema: &str) -> Result<Vec<String>> {
    let mut out = vec![
        format!("-- PostgreSQL schema dump for {database}.{schema}"),
        "-- Generated by pg".to_string(),
        String::new(),
    ];

    if schema != "public" {
        out.push(format!("CREATE SCHEMA IF NOT EXISTS {schema};"));
        out.push(String::new());
    }

    let sequences = client.query(
        "SELECT sequence_name::text, start_value::text, minimum_value::text,
                maximum_value::text, increment::text, cycle_option::text
         FROM information_schema.sequences
         WHERE sequence_schema = $1
         ORDER BY sequence_name",
        &[&schema],
    )?;
    if !sequences.is_empty() {
        out.push("-- Sequences".into());
    }
    for seq in &sequences {
        let s = |i| seq.get::<_, String>(i);
        let cycle = if s(5) == "YES" { "CYCLE" } else { "NO CYCLE" };
        out.push(format!("CREATE SEQUENCE {schema}.{}", s(0)));
        out.push(format!("    INCREMENT BY {}", s(4)));
        out.push(format!("    MINVALUE {}", s(2)));
        out.push(format!("    MAXVALUE {}", s(3)));
        out.push(format!("    START WITH {}", s(1)));
        out.push(format!("    {cycle};"));
        out.push(String::new());
    }

    let tables = client.query(
        "SELECT tablename::text FROM pg_tables WHERE schemaname = $1 ORDER BY tablename",
        &[&schema],
    )?;
    if !tables.is_empty() {
        out.push("-- Tables".into());
        out.push(String::new());
    }
    for t in &tables {
        let table: String = t.get(0);
        out.push(format!("CREATE TABLE {schema}.{table} ("));
        out.push(table_body(client, schema, &table)?.join(",\n"));
        out.push(");".into());
        out.push(String::new());
    }

    let indexes = client.query(
        "SELECT indexdef FROM pg_indexes
         WHERE schemaname = $1
           AND indexname NOT IN (
               SELECT constraint_name FROM information_schema.table_constraints
               WHERE table_schema = $1 AND constraint_type IN ('PRIMARY KEY', 'UNIQUE'))
         ORDER BY tablename, indexname",
        &[&schema],
    )?;
    if !indexes.is_empty() {
        out.push("-- Indexes".into());
        for idx in &indexes {
            out.push(format!("{};", idx.get::<_, String>(0)));
        }
        out.push(String::new());
    }
    Ok(out)
}

fn column_type(col: &Row) -> String {
    let data_type: String = col.get("data_type");
    let udt: String = col.get("udt_name");
    let max_len: Option<i32> = col.get("character_maximum_length");
    let prec: Option<i32> = col.get("numeric_precision");
    let scale: Option<i32> = col.get("numeric_scale");
    let sized = |base: &str| max_len.map_or(base.to_string(), |n| format!("{base}({n})"));
    match data_type.as_str() {
        "ARRAY" => format!("{}[]", udt.trim_start_matches('_')),
        "USER-DEFINED" => udt,
        "character varying" => sized("varchar"),
        "character" => sized("char"),
        "numeric" => match (prec, scale) {
            (Some(p), Some(s)) if s != 0 => format!("numeric({p},{s})"),
            (Some(p), _) => format!("numeric({p})"),
            _ => "numeric".into(),
        },
        _ => data_type,
    }
}

fn table_body(client: &mut Client, schema: &str, table: &str) -> Result<Vec<String>> {
    let mut defs = Vec::new();

    let columns = client.query(
        "SELECT column_name::text, data_type::text, udt_name::text,
                character_maximum_length::int, numeric_precision::int, numeric_scale::int,
                is_nullable::text, column_default::text
         FROM information_schema.columns
         WHERE table_schema = $1 AND table_name = $2
         ORDER BY ordinal_position",
        &[&schema, &table],
    )?;
    for col in &columns {
        let mut def = format!(
            "    {} {}",
            col.get::<_, String>("column_name"),
            column_type(col)
        );
        if let Some(d) = col.get::<_, Option<String>>("column_default") {
            def.push_str(&format!(" DEFAULT {d}"));
        }
        if col.get::<_, String>("is_nullable") == "NO" {
            def.push_str(" NOT NULL");
        }
        defs.push(def);
    }

    let pk = client.query(
        "SELECT kcu.column_name::text
         FROM information_schema.table_constraints tc
         JOIN information_schema.key_column_usage kcu
           ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
         WHERE tc.constraint_type = 'PRIMARY KEY' AND tc.table_schema = $1 AND tc.table_name = $2
         ORDER BY kcu.ordinal_position",
        &[&schema, &table],
    )?;
    if !pk.is_empty() {
        let cols: Vec<String> = pk.iter().map(|r| r.get(0)).collect();
        defs.push(format!("    PRIMARY KEY ({})", cols.join(", ")));
    }

    let uniques = client.query(
        "SELECT string_agg(kcu.column_name::text, ', ' ORDER BY kcu.ordinal_position)
         FROM information_schema.table_constraints tc
         JOIN information_schema.key_column_usage kcu
           ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
         WHERE tc.constraint_type = 'UNIQUE' AND tc.table_schema = $1 AND tc.table_name = $2
         GROUP BY tc.constraint_name",
        &[&schema, &table],
    )?;
    for u in &uniques {
        defs.push(format!("    UNIQUE ({})", u.get::<_, String>(0)));
    }

    let fks = client.query(
        "SELECT kcu.column_name::text, ccu.table_schema::text, ccu.table_name::text,
                ccu.column_name::text, rc.update_rule::text, rc.delete_rule::text
         FROM information_schema.table_constraints tc
         JOIN information_schema.key_column_usage kcu
           ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
         JOIN information_schema.constraint_column_usage ccu
           ON ccu.constraint_name = tc.constraint_name AND ccu.table_schema = tc.table_schema
         JOIN information_schema.referential_constraints rc
           ON rc.constraint_name = tc.constraint_name AND rc.constraint_schema = tc.table_schema
         WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = $1 AND tc.table_name = $2",
        &[&schema, &table],
    )?;
    for fk in &fks {
        let f = |i| fk.get::<_, String>(i);
        let mut def = format!(
            "    FOREIGN KEY ({}) REFERENCES {}.{}({})",
            f(0),
            f(1),
            f(2),
            f(3)
        );
        if f(5) != "NO ACTION" {
            def.push_str(&format!(" ON DELETE {}", f(5)));
        }
        if f(4) != "NO ACTION" {
            def.push_str(&format!(" ON UPDATE {}", f(4)));
        }
        defs.push(def);
    }

    let checks = client.query(
        "SELECT cc.check_clause::text
         FROM information_schema.check_constraints cc
         JOIN information_schema.table_constraints tc
           ON cc.constraint_name = tc.constraint_name AND cc.constraint_schema = tc.table_schema
         WHERE tc.table_schema = $1 AND tc.table_name = $2 AND tc.constraint_type = 'CHECK'
           AND cc.constraint_name::text NOT LIKE '%_not_null'",
        &[&schema, &table],
    )?;
    for c in &checks {
        defs.push(format!("    CHECK ({})", c.get::<_, String>(0)));
    }

    Ok(defs)
}
