# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "pubdeb"
version = "0.1.0"
edition.workspace = true
description = "Publish ./dist Debian packages to the apt repository"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "pubdeb"
path = "src/main.rs"

[dependencies]
