# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := pubdeb
BIN := uc-deb-publish
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := pubdeb

include ../rust.mk
