# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "mkdeb"
version = "0.1.0"
edition.workspace = true
description = "Make Debian packages with ease"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "uc-deb-build"
path = "src/main.rs"

[dependencies]
serde_json = { workspace = true, features = ["preserve_order"] }
