# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "k8s_ddl"
version = "0.1.0"
edition.workspace = true
description = "Create the Kubernetes resources table schema with pg"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "k8s_ddl"
path = "src/main.rs"

[dependencies]
