# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "k8s_ddl"
version = "0.1.0"
edition = "2024"
description = "Create the Kubernetes resources table schema with pg"
license = "HGL"
authors = ["Hamed Ghasemzadeh <hg@evgnomon.org>"]
publish = false

[[bin]]
name = "k8s_ddl"
path = "src/main.rs"

[dependencies]

[profile.release]
strip = true
lto = true
codegen-units = 1
