# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := k8s_ddl
BIN := uc-db-resources-schema
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := k8s_ddl

include ../rust.mk
