# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := whcloud
BIN := uc-cloud-hcloud
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := whcloud

include ../rust.mk
