# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := mgo
BIN := uc-db-mongo
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := mgo

include ../rust.mk
