# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := mkarole
BIN := uc-new-role
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := mkarole

include ../rust.mk
