# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := csv2pdf
BIN := uc-data-pdf
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := csv2pdf

include ../rust.mk
