# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := ansidist
BIN := uc-repo-dist
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := ansidist

include ../rust.mk
