# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := catalyze
BIN := uc-new-workflow
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := catalyze

include ../rust.mk
