# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "y"
version = "0.1.0"
edition = "2024"
description = "Run the repository playbook with vault secrets passed via pipes"
license = "HGL"
authors = ["Hamed Ghasemzadeh <hg@evgnomon.org>"]
publish = false

[[bin]]
name = "y"
path = "src/main.rs"

[dependencies]
libc = "0.2"

[profile.release]
strip = true
lto = true
codegen-units = 1
