# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := y
BIN := uc-cloud-play-run
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := y

include ../rust.mk
