# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := shole
BIN := uc-new-script
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := shole

include ../rust.mk
