# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := ff
BIN := uc-pick-file
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := ff

include ../rust.mk
