# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

snippet aptget "Description" b
RUN apt-get update && \
		apt-get install -y --no-install-recommends $1 && \
		rm -rf /var/lib/apt/lists/*
endsnippet
