# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "ykattach"
version = "0.1.0"
edition = "2024"
description = "Attach a YubiKey to WSL via usbipd and show its info"
license = "HGL"
authors = ["Hamed Ghasemzadeh <hg@evgnomon.org>"]
publish = false

[[bin]]
name = "ykattach"
path = "src/main.rs"

[dependencies]

[profile.release]
strip = true
lto = true
codegen-units = 1
