# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := ykattach
BIN := uc-sys-yubikey
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := ykattach

include ../rust.mk
