# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "certgen"
version = "0.1.0"
edition = "2024"
description = "X.509 certificate management (local CA, server and client certificates) via openssl"
license = "HGL"
authors = ["Hamed Ghasemzadeh <hg@evgnomon.org>"]
publish = false

[[bin]]
name = "certgen"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
