# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := certgen
BIN := uc-cert-gen
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := certgen

include ../rust.mk
