# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := ytdump
BIN := uc-media-yt
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := ytdump

include ../rust.mk
