# Copyright (C) <2025> Hamed Ghasemzadeh. All rights reserved.
# License: HGL General License <http://evgnomon.org/docs/hgl>
#
# DO NOT EDIT THIS FILE.
# THIS FILE IS AUTO-GENERATED BY BLUEPRINT.
#
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# rbenv function
rbenv() {
    local command="$1"
    shift

    case "$command" in
        rehash|shell)
            eval "$(command rbenv "sh-$command" "$@")"
            ;;
        *)
            command rbenv "$command" "$@"
            ;;
    esac
}

status() {
    local code=$?
    echo "Exit status: $code"

    case $code in
        0)   echo "✓ Success" ;;
        1)   echo "✗ General error" ;;
        2)   echo "✗ Misuse of shell command" ;;
        126) echo "✗ Command cannot execute" ;;
        127) echo "✗ Command not found" ;;
        130) echo "✗ Terminated by Ctrl+C" ;;
        *)   echo "✗ Error code $code" ;;
    esac
}

function j {
    if [ $# -eq 0 ]; then
        jobs
    elif [ $# -eq 1 ] && [[ $1 =~ ^[0-9]+$ ]]; then
        fg $1
    else
        "$@" &> /dev/null &
    fi
}

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

alias ..='cd ..'
alias ls='ls --color=auto --group-directories-first -a'
alias ll='ls -lAh --color=auto'
alias ports='netstat -tulanp'
alias myip='curl -s ifconfig.me; echo'
alias meminfo='free -m -l -t'
alias gpu='git push --set-upstream origin $(git branch --show-current)'
alias pr='az repos pr create --target-branch master --title'
alias fd='fd -I --hidden --exclude .git'
alias rg='rg --hidden -i --glob "!{.git}/**"'
alias vr="vim \$(fd . / --type file --type symlink | fzf --preview='bat --color=always --style=numbers {}')"
alias vd="vim \$(fd . ~ --type file --type symlink | fzf --preview='bat --color=always --style=numbers {}')"
alias vv="vim \$(fd . . --type file --type symlink | fzf --preview='bat --color=always --style=numbers {}')"
alias v=vim
alias g=git
alias gg=goose
alias a=claude
alias i=invoke
alias c='cd ~ && claude --disallowedTools "Read,Edit,Write,Bash,Glob,Grep"'
alias mkpass="bp vault gen pass"
alias z=fzurls
alias r='gg run --recipe'
alias d='cd "$(fd --type d | fzf)"'
alias gr="gotorepo"
alias cn='cn --config ~/.continue/config.yaml'
