# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := repofqn
BIN := uc-repo-fqn
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := repofqn

include ../rust.mk
