# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "mkunit"
version = "0.1.0"
edition.workspace = true
description = "Create a systemd unit file to run a command"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "uc-new-unit"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
