# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := mkunit
BIN := uc-new-unit
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := mkunit

include ../rust.mk
