# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "barge"
version = "0.1.0"
edition.workspace = true
description = "Run the barge container against the current directory"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "uc-image-run-barge"
path = "src/main.rs"

[dependencies]
