# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := barge
BIN := uc-image-run-barge
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := barge

include ../rust.mk
