# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "fzurls"
version = "0.1.0"
edition.workspace = true
description = "Open URLs, files, searches or fzf-picked bookmarks in Brave"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "fzurls"
path = "src/main.rs"

[dependencies]
serde_json = { workspace = true, features = ["preserve_order"] }
