# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "x"
version = "0.1.0"
edition.workspace = true
description = "Shorthand for uc configure"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "x"
path = "src/main.rs"

[dependencies]
