# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "vm"
version = "0.7.0"
edition.workspace = true
description = "A lightweight KVM/QEMU virtual machine creation tool"
license.workspace = true
authors.workspace = true

[lib]
name = "vm"
path = "src/lib.rs"

[[bin]]
name = "uc-vm-local"
path = "src/main.rs"

[build-dependencies]
cc = "1"
