# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "keychain"
version = "0.1.0"
edition = "2024"
description = "Create or edit an ansible-vault encrypted secret file"
license = "HGL"
authors = ["Hamed Ghasemzadeh <hg@evgnomon.org>"]
publish = false

[[bin]]
name = "keychain"
path = "src/main.rs"

[dependencies]
libc = "0.2"

[profile.release]
strip = true
lto = true
codegen-units = 1
