# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

[package]
name = "imgpress"
version = "0.1.0"
edition.workspace = true
description = "Compress JPEG images in a directory with ImageMagick"
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "imgpress"
path = "src/main.rs"

[dependencies]
