# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

- name: Load development environment
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - evgnomon.usecode
  roles:
    - role: logger
