# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := yacht
BIN := uc-image-run-yacht
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := yacht

include ../rust.mk
