# License-Identifier: HGL
# Copyright (C) The Usecode Authors (see AUTHORS)

NAME := ipmesh
BIN := uc-net-ipsec
# The old name, kept for a release so scripts calling it carry on working.
ALIASES := ipmesh

include ../rust.mk
