name: Make
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '*'
  delete:

jobs:
  ci:
    runs-on: ubuntu-latest
    if: >-
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'delete' &&
       github.event.ref_type == 'branch' &&
       github.event.ref != 'main')
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Make CI
        run: make ci
        env:
          VAULT_FILE: ${{ secrets.VAULT_FILE }}
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
